# Generated by Django 3.1.7 on 2021-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('original_url', models.URLField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
