# Generated by Django 3.1.7 on 2021-03-24 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20210324_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='create_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
