# Generated by Django 3.1.7 on 2021-03-24 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20210324_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='create_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
